### ISSUE TITLE
vpc error

### ISSUE THREAD

**Issue by HamadaKoji** [aws-samples/aws-fargate-fast-autoscaler#1]
Thank you for the wonderful repository! !
When I tried it in my environment, the following error occurred.

```bash
$ cdk --version
1.9.0 (build 30f158a)
$ cdk synth
There are no 'Private' subnets in this VPC.Use a different VPC subnet selection.
Subprocess exited with error 1
```

Since the contents of the default VPC vary depending on the environment, it is better to create a new VPC than to use the default VPC.

`cdk-stack.ts`

```typescript
    const vpc = new ec2.Vpc(this, 'FargateAutoScalerVPC');
```

**Comment by pahud** [comment]
Hi

Yes. You can always create a new VPC but each account will have a soft limit of max 5 VPCs in a region. If you have many CDK testing running in the same region, you may run out of available VPCs.

In addition,

```js
    const vpc = new ec2.Vpc(this, 'FargateAutoScalerVPC');
```

This will create a new VPC with 3 public subnets, 3 private subnets, 3 NATs. It not only takes a lot of time but also may consume all your available EIPs (each NAT will use 1 EIP).

I would suggest always use default VPC when testing CDK scripts. You can make sure you have 3 public subnets and 3 private subnets in your default VPC.

If you really want to create a new VPC, I suggest `natGateways: 1`

check this sample:

https://github.com/pahud/cdk-samples/blob/01a6cb9411942b9a36396aefef84c00cba3a1b5c/typescript/lib/vpc.ts#L12-L15

**Comment by HamadaKoji** [comment]
OK, thank you for your prompt reply!

Certainly, the “new vpc” configuration is expensive, and I need to be aware of the upper limit on the number of VPCs and EIPs.

I'm writing a blog now. I will be using your simple VPC sample code!

**Comment by pahud** [comment]
@HamadaKoji 

No problem. Let me know if you need any other samples. I'll do as much as I can.
