### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jeeslo** [aws-samples/aws-fargate-fast-autoscaler#5]
Hi,

After following the instructions listed in the README, I am getting an error while trying to synthesize the CF template before deploying the solution:
`$cdk synth
  Cannot read property 'length' of undefined
  Subprocess exited with error 1` 

Any idea what might be going on? 

Thanks.

**Comment by fahad-shaikh09** [comment]
any updates on this issue, as its closed without any solution?
