### ISSUE TITLE
missing package.json?

### ISSUE THREAD

**Issue by flashflexpro** [aws-samples/aws-fargate-fast-autoscaler#8]
$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/aws-fargate-fast-autoscaler/cdk/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/aws-fargate-fast-autoscaler/cdk/package.json'
npm WARN cdk No description
npm WARN cdk No repository field.
npm WARN cdk No README data
npm WARN cdk No license field.

up to date in 0.542s
found 0 vulnerabilities

**Comment by pahud** [comment]
thanks for the report. Will update and refresh this repo shortly.

**Comment by pahud** [comment]
Hi

I've refreshed this repo and published as `cdk-fargate-fastautoscaler` construct lib for npmjs and pypi.

Feel free to follow the sample in the README to build your own CDK app and let me know if it works.

It's yet fully tested but should deploy without any error.
